# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9808817b0fa9f322604909b38e0ab0a488849742853cc2eba2ff2479fb6c50f6a5f539a28320bc466f46ea97e088fc63eb11c82a887368d12efc653b05fbd694

test:
  secret_key_base: 8a6b4b8827e11a6000ec4b4bfeb23f52e09c0b3425093a042f8a8060b68fb67b267e092107364b80d9e6ff4770a3df4477934d6f424fe9a60d0f5b72f73ea027

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
